version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:17"
      timezone: America/New_York
    groups:
      python-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:37"
      timezone: America/New_York
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
